### ISSUE TITLE
update existing modules to handle new shutdown

### ISSUE THREAD

**Issue by dbenge** [AdobeAtAdobe/SimpleSensor_contrib#28]
## Expected Behavior
when main process shutsdown and sends out shutdown command all modules should clean up and stop running.  

## Actual Behavior
Modules are using old way of listening and not exiting which hangs shutdown

if (message.topic=="SHUTDOWN" and message.sender_id=='main')

## Environment details (OS, Python/package versions, any other hardware)
- python 3.6
- windows and all

**Comment by maxakuru** [comment]
This is fixed on contrib, but still an issue on SimpleSensor. Closing this, opening new issue there.
