### ISSUE TITLE
btle_beacon : update client registry to use mac as key and not uuid

### ISSUE THREAD

**Issue by dbenge** [AdobeAtAdobe/SimpleSensor_contrib#32]
## Expected Behavior
We need a safe way to deal with different beacon setups in the client registry.  
today we store in the registry by uuid as the key, we ran into a vendor that uses the same uuid for all beacons.  
we need to able to store and track each ibeacon's response data over time

## Actual Behavior
we store by uuid which is a writable value that can be used by the ibeacon vendor as they see fit
in the case where the vendor set it to be the same value we will only see one client come and go in the detection area.

**Comment by maxakuru** [comment]
Done, a while back
